version: 2

project_name: task-compose

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

universal_binaries:
  - replace: false

builds:
  - id: "task-compose-cli-build"
    binary: "task-compose"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/app.Version={{.Version}}
      - -X {{.ModulePath}}/app.CommitHash={{.ShortCommit}}
      - -X {{.ModulePath}}/app.BuildDate={{.CommitDate}}
      - -X {{.ModulePath}}/app.ExecutionMode=CLI
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: "task-compose-portable-build"
    binary: "task-compose-portable"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{.ModulePath}}/app.Version={{.Version}}
      - -X {{.ModulePath}}/app.CommitHash={{.ShortCommit}}
      - -X {{.ModulePath}}/app.BuildDate={{.CommitDate}}
      - -X {{.ModulePath}}/app.ExecutionMode=GUI
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: "task-compose-cli-archive"
    formats: ['tar.gz']
    ids:
      - task-compose-cli-build
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
  - id: "task-compose-portable-archive"
    formats: ['tar.gz']
    ids:
      - task-compose-portable-build
    name_template: "{{ .ProjectName }}-portable_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: vulcanshen-tpi
    name: task-compose
  name_template: "Release {{ .Tag }}"


homebrew_casks:
  - name: task-compose
    repository:
      owner: vulcanshen-tpi
      name: homebrew-tap
    homepage: "https://github.com/vulcanshen-tpi/task-compose"
    description: "Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
    license: "MIT"
    ids:
      - task-compose-cli-archive

scoops:
  - repository:
      owner: vulcanshen-tpi
      name: scoop-bucket
    directory: bucket
    homepage: "https://github.com/vulcanshen-tpi/task-compose"
    description: "A command orchestration tool for declarative task execution."
    license: MIT
    ids:
      - task-compose-cli-archive

dockers:
  - id: "task-compose-docker-amd64"
    ids:
      - task-compose-cli-build
    use: buildx
    goarch: amd64
    image_templates:
      - "vulcantpisoft/task-compose:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.description=Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - README.md
      - LICENSE
  - id: "task-compose-docker-arm64"
    use: buildx
    goarch: arm64
    image_templates:
      - "vulcantpisoft/task-compose:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.description=Designed to orchestrate and execute a series of commands based on a declarative YAML configuration file."
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - README.md
      - LICENSE

docker_manifests:
  - name_template: "vulcantpisoft/task-compose:{{ .Version }}"
    image_templates:
      - "vulcantpisoft/task-compose:{{ .Version }}-amd64"
      - "vulcantpisoft/task-compose:{{ .Version }}-arm64"
  - name_template: "vulcantpisoft/task-compose:latest"
    image_templates:
      - "vulcantpisoft/task-compose:{{ .Version }}-amd64"
      - "vulcantpisoft/task-compose:{{ .Version }}-arm64"


snapshot:
  version_template: "{{ .Version }}-snapshot"

gomod:
  proxy: true

report_sizes: true

#sboms:
#  - artifacts: archive

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ with .AuthorUsername }} (@{{ . }}){{ end }}"
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: update$"
      - "^chore: docs$"
      - "^docs: update$"
      - "^chore: schema$"
      - "^chore: typo$"
      - "^chore: auto-update generated files$"
      - "^chore: update schema$"
      - "^chore: schema update$"
      - "^chore\\(deps\\): "
      - "^(build|ci): "
      - "merge conflict"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999